# git tasks
- name: Create git template directories.
  file: name={{ansible_env.HOME}}/.config/git state=directory

- name: Copy git templates.
  template: src={{item.key}} dest={{item.value}}
  with_dict:
    ../templates/git/ignore.j2: "{{ansible_env.HOME}}/.config/git/ignore"
    ../templates/git/config.j2: "{{ansible_env.HOME}}/.gitconfig"
