# git tasks
- name: Set local git config.
  set_fact: git_config_email={{ansible_local.dotfiles.git.git_config_email}}
  when: ansible_local.dotfiles.git.git_config_email is defined

- name: Create git template directories.
  file: name={{ansible_env.HOME}}/.config/git state=directory

- name: Copy git templates.
  template: src={{item.key}} dest={{item.value}}
  with_dict:
    ../templates/git/ignore.j2: "{{ansible_env.HOME}}/.config/git/ignore"
    ../templates/git/config.j2: "{{ansible_env.HOME}}/.gitconfig"
