# zsh tasks
- name: Change shell.
  user: name={{ ansible_user_id }} shell=/bin/zsh
  become: yes

- name: Run oh-my-zsh install script.
  raw: /bin/sh -c "$(curl -fsSL {{oh_my_zsh_install_url}})"

- name: Modify oh-my-zsh plugins.
  lineinfile:
    dest: "{{ansible_env.HOME}}/.zshrc"
    line: plugins=({{oh_my_zsh_plugins}})
    regexp: ^plugins=
