# zsh tasks
- name: Change shell.
  raw: /usr/bin/chsh -s $(which zsh)
  when: not ('zsh' in lookup('env','SHELL'))
  become: yes

- name: Run oh-my-zsh install script.
  raw: /bin/sh -c "$(curl -fsSL {{oh_my_zsh_install_url}})"

- name: Modify oh-my-zsh plugins.
  lineinfile:
    dest: "{{ansible_env.HOME}}/.zshrc"
    line: plugins=({{oh_my_zsh_plugins}})
    regexp: ^plugins=
